name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Build
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smog-linux
          path: dist/smog-linux.tar.gz
          retention-days: 14

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Build
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh darwin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smog-darwin
          path: dist/smog-darwin.tar.gz
          retention-days: 14

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Build
        shell: bash
        run: ./scripts/build.sh windows

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smog-windows
          path: dist/smog-windows.tar.gz
          retention-days: 14
